// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;
using Slate.Server.Data;

#nullable disable

namespace Slate.Server.Data.Migrations
{
    [DbContext(typeof(SlateDbContext))]
    partial class SlateDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Slate.Server.Domain.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Mime")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mime");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<Guid>("VaultId")
                        .HasColumnType("uuid")
                        .HasColumnName("vault_id");

                    b.HasKey("Id")
                        .HasName("pk_attachments");

                    b.HasIndex("VaultId", "Path")
                        .IsUnique()
                        .HasDatabaseName("ix_attachments_vault_id_path");

                    b.ToTable("attachments", (string)null);
                });

            modelBuilder.Entity("Slate.Server.Domain.ExternalLogin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_external_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_external_logins_user_id");

                    b.HasIndex("Provider", "Subject")
                        .IsUnique()
                        .HasDatabaseName("ix_external_logins_provider_subject");

                    b.ToTable("external_logins", (string)null);
                });

            modelBuilder.Entity("Slate.Server.Domain.Invite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid?>("UsedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("used_by");

                    b.HasKey("Id")
                        .HasName("pk_invites");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_invites_created_by");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_invites_token_hash");

                    b.HasIndex("UsedBy")
                        .HasDatabaseName("ix_invites_used_by");

                    b.ToTable("invites", (string)null);
                });

            modelBuilder.Entity("Slate.Server.Domain.Link", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("SourceNoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_note_id");

                    b.Property<Guid?>("TargetNoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_note_id");

                    b.Property<string>("TargetText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target_text");

                    b.HasKey("Id")
                        .HasName("pk_links");

                    b.HasIndex("SourceNoteId")
                        .HasDatabaseName("ix_links_source_note_id");

                    b.HasIndex("TargetNoteId")
                        .HasDatabaseName("ix_links_target_note_id");

                    b.ToTable("links", (string)null);
                });

            modelBuilder.Entity("Slate.Server.Domain.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("HasConflict")
                        .HasColumnType("boolean")
                        .HasColumnName("has_conflict");

                    b.Property<long?>("HeadRevId")
                        .HasColumnType("bigint")
                        .HasColumnName("head_rev_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .HasColumnType("tsvector")
                        .HasColumnName("search_vector");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("VaultId")
                        .HasColumnType("uuid")
                        .HasColumnName("vault_id");

                    b.HasKey("Id")
                        .HasName("pk_notes");

                    b.HasIndex("HeadRevId")
                        .HasDatabaseName("ix_notes_head_rev_id");

                    b.HasIndex("SearchVector")
                        .HasDatabaseName("ix_notes_search_vector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "gin");

                    b.HasIndex("VaultId", "Path")
                        .IsUnique()
                        .HasDatabaseName("ix_notes_vault_id_path")
                        .HasFilter("is_deleted = false");

                    b.ToTable("notes", (string)null);
                });

            modelBuilder.Entity("Slate.Server.Domain.NoteTag", b =>
                {
                    b.Property<Guid>("NoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("note_id");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.HasKey("NoteId", "TagId")
                        .HasName("pk_note_tags");

                    b.HasIndex("TagId")
                        .HasDatabaseName("ix_note_tags_tag_id");

                    b.ToTable("note_tags", (string)null);
                });

            modelBuilder.Entity("Slate.Server.Domain.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DeviceName")
                        .HasColumnType("text")
                        .HasColumnName("device_name");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Slate.Server.Domain.Revision", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid?>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("device_id");

                    b.Property<bool>("IsConflict")
                        .HasColumnType("boolean")
                        .HasColumnName("is_conflict");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<Guid?>("NoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("note_id");

                    b.Property<string>("OldPath")
                        .HasColumnType("text")
                        .HasColumnName("old_path");

                    b.Property<long?>("ParentRevId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_rev_id");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.Property<Guid>("VaultId")
                        .HasColumnType("uuid")
                        .HasColumnName("vault_id");

                    b.HasKey("Id")
                        .HasName("pk_revisions");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_revisions_author_id");

                    b.HasIndex("NoteId")
                        .HasDatabaseName("ix_revisions_note_id");

                    b.HasIndex("ParentRevId")
                        .HasDatabaseName("ix_revisions_parent_rev_id");

                    b.HasIndex("VaultId", "Id")
                        .HasDatabaseName("ix_revisions_vault_id_id");

                    b.ToTable("revisions", (string)null);
                });

            modelBuilder.Entity("Slate.Server.Domain.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("VaultId")
                        .HasColumnType("uuid")
                        .HasColumnName("vault_id");

                    b.HasKey("Id")
                        .HasName("pk_tags");

                    b.HasIndex("VaultId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_tags_vault_id_name");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("Slate.Server.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_disabled");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Slate.Server.Domain.Vault", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.HasKey("Id")
                        .HasName("pk_vaults");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_vaults_owner_id");

                    b.ToTable("vaults", (string)null);
                });

            modelBuilder.Entity("Slate.Server.Domain.VaultMember", b =>
                {
                    b.Property<Guid>("VaultId")
                        .HasColumnType("uuid")
                        .HasColumnName("vault_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Access")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("access");

                    b.HasKey("VaultId", "UserId")
                        .HasName("pk_vault_members");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_vault_members_user_id");

                    b.ToTable("vault_members", (string)null);
                });

            modelBuilder.Entity("Slate.Server.Domain.Attachment", b =>
                {
                    b.HasOne("Slate.Server.Domain.Vault", "Vault")
                        .WithMany("Attachments")
                        .HasForeignKey("VaultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_attachments_vaults_vault_id");

                    b.Navigation("Vault");
                });

            modelBuilder.Entity("Slate.Server.Domain.ExternalLogin", b =>
                {
                    b.HasOne("Slate.Server.Domain.User", "User")
                        .WithMany("ExternalLogins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_external_logins_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Slate.Server.Domain.Invite", b =>
                {
                    b.HasOne("Slate.Server.Domain.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_invites_users_created_by");

                    b.HasOne("Slate.Server.Domain.User", "UsedByUser")
                        .WithMany()
                        .HasForeignKey("UsedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_invites_users_used_by");

                    b.Navigation("CreatedByUser");

                    b.Navigation("UsedByUser");
                });

            modelBuilder.Entity("Slate.Server.Domain.Link", b =>
                {
                    b.HasOne("Slate.Server.Domain.Note", "SourceNote")
                        .WithMany("OutgoingLinks")
                        .HasForeignKey("SourceNoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_links_notes_source_note_id");

                    b.HasOne("Slate.Server.Domain.Note", "TargetNote")
                        .WithMany("IncomingLinks")
                        .HasForeignKey("TargetNoteId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_links_notes_target_note_id");

                    b.Navigation("SourceNote");

                    b.Navigation("TargetNote");
                });

            modelBuilder.Entity("Slate.Server.Domain.Note", b =>
                {
                    b.HasOne("Slate.Server.Domain.Revision", "HeadRevision")
                        .WithMany()
                        .HasForeignKey("HeadRevId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_notes_revisions_head_rev_id");

                    b.HasOne("Slate.Server.Domain.Vault", "Vault")
                        .WithMany("Notes")
                        .HasForeignKey("VaultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notes_vaults_vault_id");

                    b.Navigation("HeadRevision");

                    b.Navigation("Vault");
                });

            modelBuilder.Entity("Slate.Server.Domain.NoteTag", b =>
                {
                    b.HasOne("Slate.Server.Domain.Note", "Note")
                        .WithMany("NoteTags")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_note_tags_notes_note_id");

                    b.HasOne("Slate.Server.Domain.Tag", "Tag")
                        .WithMany("NoteTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_note_tags_tags_tag_id");

                    b.Navigation("Note");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Slate.Server.Domain.RefreshToken", b =>
                {
                    b.HasOne("Slate.Server.Domain.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Slate.Server.Domain.Revision", b =>
                {
                    b.HasOne("Slate.Server.Domain.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_revisions_users_author_id");

                    b.HasOne("Slate.Server.Domain.Note", "Note")
                        .WithMany("Revisions")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_revisions_notes_note_id");

                    b.HasOne("Slate.Server.Domain.Revision", "ParentRevision")
                        .WithMany()
                        .HasForeignKey("ParentRevId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_revisions_revisions_parent_rev_id");

                    b.HasOne("Slate.Server.Domain.Vault", "Vault")
                        .WithMany("Revisions")
                        .HasForeignKey("VaultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_revisions_vaults_vault_id");

                    b.Navigation("Author");

                    b.Navigation("Note");

                    b.Navigation("ParentRevision");

                    b.Navigation("Vault");
                });

            modelBuilder.Entity("Slate.Server.Domain.Tag", b =>
                {
                    b.HasOne("Slate.Server.Domain.Vault", "Vault")
                        .WithMany("Tags")
                        .HasForeignKey("VaultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tags_vaults_vault_id");

                    b.Navigation("Vault");
                });

            modelBuilder.Entity("Slate.Server.Domain.Vault", b =>
                {
                    b.HasOne("Slate.Server.Domain.User", "Owner")
                        .WithMany("OwnedVaults")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vaults_users_owner_id");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Slate.Server.Domain.VaultMember", b =>
                {
                    b.HasOne("Slate.Server.Domain.User", "User")
                        .WithMany("VaultMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vault_members_users_user_id");

                    b.HasOne("Slate.Server.Domain.Vault", "Vault")
                        .WithMany("Members")
                        .HasForeignKey("VaultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vault_members_vaults_vault_id");

                    b.Navigation("User");

                    b.Navigation("Vault");
                });

            modelBuilder.Entity("Slate.Server.Domain.Note", b =>
                {
                    b.Navigation("IncomingLinks");

                    b.Navigation("NoteTags");

                    b.Navigation("OutgoingLinks");

                    b.Navigation("Revisions");
                });

            modelBuilder.Entity("Slate.Server.Domain.Tag", b =>
                {
                    b.Navigation("NoteTags");
                });

            modelBuilder.Entity("Slate.Server.Domain.User", b =>
                {
                    b.Navigation("ExternalLogins");

                    b.Navigation("OwnedVaults");

                    b.Navigation("RefreshTokens");

                    b.Navigation("VaultMemberships");
                });

            modelBuilder.Entity("Slate.Server.Domain.Vault", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Members");

                    b.Navigation("Notes");

                    b.Navigation("Revisions");

                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
